version: '3'

volumes:
  production_static: {}

services:
  production_django: &django
    container_name: cinemapi_production_django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    volumes:
      - production_static:/app/staticfiles
    image: cinemapi_production_django
    env_file:
      - .envs/.production
    expose:
      - "8000"
    command: /start
    restart: always

  nginx:
    container_name: cinema_nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - production_static:/static
      - ./ssl/:/ssl
    ports:
      - "80:80"
    depends_on:
      - production_django
    restart: always
