# Generated by Django 2.2.8 on 2020-08-15 03:15

import cinemapi.movies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('overview', models.TextField()),
                ('release_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1878), cinemapi.movies.models.max_value_current_year])),
            ],
        ),
    ]
