#!/bin/sh

set -o errexit
# set -o pipefail
set -o nounset


python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py collectstatic --noinput
gunicorn config.wsgi:application --user django --timeout 1000 --workers 4 --bind 0.0.0.0:8000 --chdir=/app
